Cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app.views import main_view
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view,login_view, logout_view
urlpatterns = [
    path('admin/', admin.site.urls),

    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),

    path('', main_view)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.core.validators import RegexValidator # Для регулних виразів

# Create your models here.
class DishCategory(models.Model):
    title = models.CharField(max_length=50, unique=True)
    position = models.PositiveIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)

    def __iter__(self):
        for dish in self.dishes.filter(is_visible=True):
            yield dish

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ('position',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Dish(models.Model):
    title = models.CharField(max_length=50, unique=True)
    position = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True)
    category = models.ForeignKey(DishCategory, related_name='dishes', on_delete=models.CASCADE)
    is_special = models.BooleanField(default=False)
    is_signature = models.BooleanField(default=False)
    desc = models.TextField(max_length=200, blank=True, verbose_name='about dish')
    price = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    ingredients = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='dishes')
    is_recommended = models.BooleanField(default=False)

    def total_price(self):
        return self.price - self.discount / 100 * self.price

    class Meta:
        ordering = ('position',)
        verbose_name = 'Dish'
        verbose_name_plural = "Dishes"

    def __str__(self):
        return f'{self.title}'


class Reservation(models.Model):
    phone_validator = RegexValidator(regex='^\+?3?8?0?\d{2}[ -]?(\d[ -]?){7}$',
                                     message='Phone number is waited in format +380xx xxx xx xx')
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=16, validators=(phone_validator,))
    visit_datetime = models.DateField()
    date_request = models.DateTimeField(auto_now_add=True)
    date_response = models.DateTimeField(auto_now=True)
    guests = models.CharField(max_length=10)
    message = models.TextField(max_length=1000, blank=True)
    is_processed = models.BooleanField(default=False)



    class Meta:
        ordering = ('-date_request', )

    def __str__(self):
        return f'{self.name}\t{self.phone}\t{self.email}'

class About(models.Model):
    heading = models.CharField(max_length=50, unique=True)
    desc_history = models.TextField(max_length=3000)


    class Meta:
        verbose_name = 'About'
        verbose_name_plural = "Abouts"

    def __str__(self):
        return f'{self.heading}\t{self.desc_history}'


class Service(models.Model):
    icon_choices = [
        ("H", " heart"),
        ("T", "user-tie"),
        ("HAM", "hamburger")
    ]

    title = models.CharField(max_length=50, unique=True)
    position = models.PositiveSmallIntegerField()
    desc = models.TextField(max_length=3000, verbose_name='about services')
    is_visible = models.BooleanField(default=True)
    icon = models.CharField(max_length=3, choices=icon_choices, default="H")

    class Meta:
        ordering = ('position',)
        verbose_name = 'Service'
        verbose_name_plural = "Services"

    def __str__(self):
        return f'{self.title}'

class Gallery(models.Model):
    title = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to='media/')

    def __str__(self):
        return f'{self.title}'

main_app/forms.py
from django import forms
from .models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('name', 'email', 'phone', 'visit_datetime', 'guests', 'message')

    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                                         'id': "resName",
                                                                         'type': "text",
                                                                         'name': "res_name",
                                                                         'required': "",
                                                                         }))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                           'id': "resEmail",
                                                           'type': "email",
                                                           'name': "res_email",
                                                           'required': "",
                                                           }))
    phone = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                                         'id': "resNumber",
                                                                         'type': "number",
                                                                         'name': "res_number",
                                                                         'required': "",
                                                                         }))
    visit_datetime = forms.DateField(input_formats=['%d.%m.%Y %H:%M'], widget=forms.DateTimeInput(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                             'id': "resDate",
                                                             'type': "text",
                                                             'name': "res_date",
                                                             'required': "",
                                                             }, format='%d.%m.%Y %H:%M'))
    guests = forms.IntegerField(widget=forms.NumberInput(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                                 'id': "resPeople",
                                                                 'type': "number",
                                                                 "name": "res_people",
                                                                 'required': "",
                                                                 }))
    message = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': "form-control shadow-0 px-0 border-0 border-bottom",
                                                                            'id': "request",
                                                                            'rows': "7",
                                                                            'name': "res_request",
                                                                            'required': "",
                                                                            }))

    def clean(self):
        import datetime
        if 'date' not in self.cleaned_data:
            self.cleaned_data['date'] = datetime.datetime.now()
        return super().clean()

main_app/views.py
from django.shortcuts import render, redirect
from .models import DishCategory, Dish, About, Service, Gallery
from .forms import ReservationForm
# Create your views here.
def main_view(request):
    if request.method == 'POST':
        form_reserve = ReservationForm(request.POST)
        if form_reserve.is_valid():
            form_reserve.save()
            return redirect('/')

    categories = DishCategory.objects.filter(is_visible=True)
    dishes = Dish.objects.filter(is_visible=True, is_special=False, is_signature=False)
    special_dishes = Dish.objects.filter(is_visible=True, is_special=True)
    signature_dishes = Dish.objects.filter(is_visible=True, is_signature=True)
    about = About.objects.get()
    services = Service.objects.filter(is_visible=True)
    galleries = Gallery.objects.all()
    form_reserve = ReservationForm()
    return render(request, 'main_page.html', context={
        'categories': categories,
        'dishes': dishes,
        'special_dishes': special_dishes,
        'signature_dishes': signature_dishes,
        'about': about,
        'services': services,
        'galleries': galleries,
        'form_reserve': form_reserve,



    })

main_app/templates/Serv.html
    <section id="services">
      <div class="container text-center">
        <header class="mb-5">
          <h2 class="handwriting-text">We provide the following</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Our Specialities</h5>
        </header>
        <div class="row gy-4">
          {% for service in services %}
                        <div class="hover-icon-primary col-md-4">
            <div class="icon mb-4 mx-auto"><i class="far fa-heart"></i></div>
{#            <div class="icon mb-4 mx-auto"><i class="fas fa-user-tie"></i></div>#}
{#            <div class="icon mb-4 mx-auto"><i class="fas fa-hamburger"></i></div>#}
            <h5 class="text-uppercase">{{service.title}}</h5>
            <p class="mb-0 text-muted">{{service.desc}}</p>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

main_app/templates/Serv2.html
    <section id="services">
      <div class="container text-center">
        <header class="mb-5">
          <h2 class="handwriting-text">We provide the following</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Our Specialities</h5>
        </header>
        <div class="row gy-4">
          <!-- item-->
            {% for service in services %}
                <div class="hover-icon-primary col-md-4">
                    <div class="icon mb-4 mx-auto">
                        {% if service.icon == "H" %}
                            <i class="far fa-heart"></i>
                        {% endif %}
                        {% if service.icon == "T" %}
                            <i class="fas fa-user-tie"></i>
                        {% endif %}
                        {% if service.icon == "HAM" %}
                            <i class="fas fa-hamburger"></i>
                        {% endif %}
                    </div>
                    <h5 class="text-uppercase">{{service.title}}</h5>
                    <p class="mb-0 text-muted">{{service.desc}}</p>
                </div>
            {% endfor %}
        </div>
      </div>
     </section>

main_app/templates/about.html
    <section class="bg-light" id="about">
      <div class="container text-center">
        <header class="mb-5">
          <h2 class="handwriting-text">About Restaurant</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">{{ about }}</h5>
        </header>
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <p class="lead text-muted mb-0"></p>
          </div>
        </div>
      </div><img class="position-absolute top-100 start-100 translate-middle d-none d-lg-block" src="img/dish-d.png" alt=" ... " width="300">
    </section>

main_app/templates/form.html
<form>
                        <div class="row gy-3">
                          <div class="col-lg-6">
                            <label class="form-label" for="resName"> Name</label>
                            <input class="form-control shadow-0 px-0 border-0 border-bottom" id="resName" type="text" name="res_name" required="">
                          </div>
                          <div class="col-lg-6">
                            <label class="form-label" for="resEmail"> Email</label>
                            <input class="form-control shadow-0 px-0 border-0 border-bottom" id="resEmail" type="email" name="res_email" required="">
                          </div>
                          <div class="col-lg-6">
                            <label class="form-label" for="resNumber"> Number</label>
                            <input class="form-control shadow-0 px-0 border-0 border-bottom" id="resNumber" type="number" name="res_number" required="">
                          </div>
                          <div class="col-lg-6">
                            <label class="form-label" for="resPeople"> People</label>
                            <input class="form-control shadow-0 px-0 border-0 border-bottom" id="resPeople" type="number" name="res_people" required="">
                          </div>
                          <div class="col-lg-12">
                            <label class="form-label" for="resDate"> Date & Time</label>
                            <input class="form-control shadow-0 px-0 border-0 border-bottom" id="resDate" type="text" name="res_date" required="">
                          </div>
                          <div class="col-lg-12">
                            <label class="form-label" for="request"> Special request</label>
                            <textarea class="form-control shadow-0 px-0 border-0 border-bottom" id="request" rows="7" name="res_request" required=""></textarea>
                          </div>
                          <div class="col-lg-12 text-center">
                            <button class="btn btn-primary" type="submit">Book now</button>
                          </div>
                        </div>
                      </form>



<!-- Booking Section-->
    <section class="bg-light" id="booking">
      <div class="container">
        <header class="text-center mb-5">
          <h2 class="handwriting-text">Order your table</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Enjoy your meal at our restaurant</h5>
        </header>
        <div class="row">
          <div class="col-lg-10 mx-auto position-relative"><img class="position-absolute top-100 start-100 translate-middle d-none d-lg-block" src="img/vegetables.png" alt="..." width="300">
            <div class="bg-white z-index-20 position-relative">
              <div class="row">
                <div class="col-lg-10 mx-auto">
                  <div class="card border-0 py-5">
                    <div class="ribbon">
                      <div class="icon icon-sm border-0 bg-primary rounded-0 text-white"><i class="fas fa-star text-white"></i></div>
                    </div>
                    <div class="card-body pt-5">
                      <header class="mb-5 text-center">
                        <h3 class="handwriting-text">Make a reservation</h3>
                        <h5 class="text-uppercase text-gray-500 fw-normal">Book your table now</h5>
                      </header>
                        <form method="post">
                            {% csrf_token %}
                      {{ form_reserve.as_p }}
                            <div class="text-center"><button type="submit">Send Message</button></div> # Кнопка Message
                            </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End Booking Section-->
    </section>

main_app/templates/gallery.html
    <section id="gallery">
      <div class="container text-center">
        <header class="mb-5">
          <h2 class="handwriting-text">Our Gallery</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Discover the photo gallery</h5>
        </header>
        <div class="row g-0">
          <!-- Item-->
            {% for item in galleries %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="overlay-hover-primary"><img class="img-fluid" src="{{item.image.url}}" alt="image">
              <div class="overlay-content p-1"><a class="glightbox d-block border border-2 border-white w-100 h-100 d-flex align-items-center justify-content-center text-white text-decoration-none" href="img/bg01.jpg" data-gallery="gallery" data-glightbox="Image Caption">
                  <div class="icon icon-md border border-white"><i class="fas fa-search fa-2x text-white"></i></div></a></div>
            </div>
          </div>
            {% endfor %}

        </div>
      </div>
    </section>

main_app/templates/main_page.html
{% extends 'index.html' %}

{% block main_content %}
    <!-- Reservation Modal-->
    <div class="modal fade" id="reservationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content position-relative">
          <div class="bg-primary position-absolute top-0 start-0 z-index-top">
            <button class="btn-close btn-close-white p-3 opacity-10" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body p-5">
            <header class="mb-5 text-center">
              <h3 class="handwriting-text">Make a reservation</h3>
              <h5 class="text-uppercase text-gray-500 fw-normal">Book your table now</h5>
            </header>
            <form class="p-lg-5">
              <div class="row gy-3">
                <div class="col-lg-6">
                  <label class="form-label" for="modalResName"> Name</label>
                  <input class="form-control shadow-0 px-0 border-0 border-bottom" id="modalResName" type="text" name="res_name" required="">
                </div>
                <div class="col-lg-6">
                  <label class="form-label" for="modalResEmail"> Email</label>
                  <input class="form-control shadow-0 px-0 border-0 border-bottom" id="modalResEmail" type="email" name="res_email" required="">
                </div>
                <div class="col-lg-6">
                  <label class="form-label" for="modalResNumber"> Number</label>
                  <input class="form-control shadow-0 px-0 border-0 border-bottom" id="modalResNumber" type="number" name="res_number" required="">
                </div>
                <div class="col-lg-6">
                  <label class="form-label" for="modalResPeople"> People</label>
                  <input class="form-control shadow-0 px-0 border-0 border-bottom" id="modalResPeople" type="number" name="res_people" required="">
                </div>
                <div class="col-lg-12">
                  <label class="form-label" for="modalResDate"> Date & Time</label>
                  <input class="form-control shadow-0 px-0 border-0 border-bottom" id="modalResDate" type="text" name="res_date" required="">
                </div>
                <div class="col-lg-12">
                  <label class="form-label" for="modalRequest"> Special request</label>
                  <textarea class="form-control shadow-0 px-0 border-0 border-bottom" id="modalRequest" rows="7" name="res_request" required=""></textarea>
                </div>
                <div class="col-lg-12 text-center">
                  <button class="btn btn-primary" type="submit">Book now</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Hero Section-->
    <section class="text-white p-0" id="hero">
      <div class="swiper hero-slider">
        <div class="swiper-wrapper">
          <div class="swiper-slide h-auto">
            <div class="hero-slide bg-center bg-cover" style="background-image: url(img/hero-bg.jpg);">
              <div class="container pe-5">
                <h2 class="handwriting-text" data-swiper-parallax="-200">This is <span class="text-primary">Italiano restaurant</span></h2>
                <h1 class="handwriting-text" data-swiper-parallax="-300">Bootstrap Template</h1>
                <p class="hero-text lh-3" data-swiper-parallax="-400">An elegant Bootstrap template brought to you by <a href="https://bootstraptemple.com/" target="_blank">Bootstrap Temple</a></p>
              </div>
            </div>
          </div>
          <div class="swiper-slide h-auto">
            <div class="hero-slide bg-center bg-cover" style="background-image: url(img/hero-bg02.jpg);">
              <div class="container pe-5">
                <h1 class="handwriting-text" data-swiper-parallax="-200">lorem ipsum dolor sit amit</h1>
                <p class="hero-text lh-3" data-swiper-parallax="-400"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
              </div>
            </div>
          </div>
          <div class="swiper-slide h-auto">
            <div class="hero-slide bg-center bg-cover" style="background-image: url(img/hero-bg03.jpg);">
              <div class="container pe-5">
                <h2 class="handwriting-text" data-swiper-parallax="-200">Visit <span class="text-primary">italiano restaurant</span></h2>
                <h1 class="handwriting-text" data-swiper-parallax="-300">lorem ipsum dolor sit amit</h1>
                <p class="hero-text lh-3" data-swiper-parallax="-400">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
              </div>
            </div>
          </div>
        </div>
        <!-- slider pagination-->
        <div class="swiper-pagination p-3 text-end"></div>
      </div><a class="scroll-down d-none d-sm-block" href="#about"></a>
      <!-- social icons menu-->
      <div class="hero-social d-none d-xl-flex">
        <ul class="list-inline mb-0">
          <li class="list-inline-item"><a class="text-reset" href="#!"><i class="fab fa-facebook-f"></i></a></li>
          <li class="list-inline-item"><a class="text-reset" href="#!"><i class="fab fa-twitter"></i></a></li>
          <li class="list-inline-item"><a class="text-reset" href="#!"><i class="fab fa-instagram"></i></a></li>
          <li class="list-inline-item"><a class="text-reset" href="#!"><i class="fab fa-pinterest"></i></a></li>
        </ul><span class="line"></span><span class="text-uppercase">Follow us</span>
      </div>
    </section>
    <section class="p-0" id="detail">
      <div class="row">
        <div class="col-lg-6 p-5 bg-black text-white">
          <div class="d-flex flex-column flex-lg-row align-items-center justify-content-center">
            <div class="text-center me-lg-2"><span>Call Us Now For</span>
              <h5 class="text-primary text-uppercase mt-2">Home Delivery</h5>
            </div>
            <div class="ms-lg-3"><a class="text-reset h3" href="tel:9870988764">987 098 8764 </a></div>
          </div>
        </div>
        <div class="col-lg-6 p-5 bg-primary">
          <div class="d-flex align-items-center justify-content-center justify-content-lg-start">
            <div class="text-center"><span class="text-black">Check Our Clients'</span>
              <h5 class="text-white text-uppercase mt-2">Rating &amp; reviews</h5>
            </div>
            <div class="ms-3"><a class="link-rounded bg-white" href="#!"> <i class="fas fa-angle-right"></i></a></div>
          </div>
        </div>
      </div>
    </section>
    <!-- About Section-->
    {% include 'about.html' %}
    <!-- End About Section-->
    <!-- Services Section-->
    {% include 'services.html' %}
    <!-- End Services Section-->
    <!-- App Section-->
    <section class="p-0" id="app">
      <div class="container">
        <div class="bg-primary text-white p-1">
          <div class="p-5 text-center border border-2">
            <h5 class="h4 mb-4 text-uppercase fw-light">Our app is available now, we made it easire, Download it now.</h5>
            <ul class="list-inline mb-0">
              <li class="list-inline-item"><a class="btn btn-light" href="https://bootstrapious.com/" title="Google Play">Google Play</a></li>
              <li class="list-inline-item"><a class="btn btn-light" href="https://bootstrapious.com/" title="Appstore">App Store</a></li>
              <li class="list-inline-item"><a class="btn btn-light" href="https://bootstrapious.com/" title="Bootstrap Temple">Download this template</a></li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <!-- End App Section-->
    <!-- Dishes Section-->

    {% include 'signature.html' %}
    <!-- End Dishes Section-->
    <!-- Offers Section-->
    {% include 'offers.html' %}



    <!-- Menu Section-->
    {% include 'menu.html' %}

    <!-- Events Section-->
    <section class="bg-light" id="events">
      <div class="container">
        <header class="text-center mb-5">
          <h2 class="handwriting-text">Upcoming Events</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Don't miss our awesome events</h5>
        </header>
        <div class="row g-0 bg-white align-items-stretch">
          <!-- Profile Side-->
          <div class="col-lg-6">
            <div class="dark-overlay p-1 bg-cover bg-center h-100" style="background-image: url(img/event-bg.jpg);">
              <div class="overlay-content border border-2 border-white text-white p-5 h-100">
                <div class="d-flex align-items-center">
                  <div class="icon icon-md rounded-0 border-2 border-white me-3">
                    <h4 class="mb-0">15</h4><sup>th</sup>
                  </div>
                  <div class="text-uppercase">
                    <p class="h3 mb-0 mb-0 lh-1 fw-normal">December </p><span class="h4">2016</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Details Side-->
          <div class="col-lg-6 bg-white p-5">
            <div class="py-5">
              <h3 class="h5 text-uppercase">Italian Master Class</h3>
              <h4 class="h6 text-primary text-uppercase mb-3">15 December 2016 | 20:00</h4>
              <p class="text-muted text-sm lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..</p><a class="btn btn-primary" href="#!">Read More</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Events Section-->
    <!-- Gallery Section-->
    {% include 'gallery.html' %}
    <!-- End Gallery Section-->
    {% include "reserve_form.html" %}
    <!-- Booking Section-->


    <!-- Contact Section-->
    <section id="contact">
      <div class="position-absolute top-0 start-0 end-0 bottom-0" id="map"></div>
      <div class="container z-index-top">
        <div class="card shadow border-0">
          <div class="card-body p-lg-5">
            <header class="text-center mb-5">
              <h2 class="handwriting-text">Contact Us</h2>
              <h5 class="text-uppercase text-gray-500 fw-normal">Feel free to contact us</h5>
            </header>
            <div class="row">
              <div class="col-lg-7 mx-auto">
                <form>
                  <div class="row gy-4">
                    <div class="col-lg-6">
                      <label class="form-label" for="name"> Name</label>
                      <input class="form-control shadow-0 px-0 border-0 border-bottom" id="name" type="text" name="name" required="">
                    </div>
                    <div class="col-lg-6">
                      <label class="form-label" for="email"> Email</label>
                      <input class="form-control shadow-0 px-0 border-0 border-bottom" id="email" type="email" name="email" required="">
                    </div>
                    <div class="col-lg-12">
                      <label class="form-label" for="message"> Your message</label>
                      <textarea class="form-control shadow-0 px-0 border-0 border-bottom" id="message" rows="7" name="message" required=""></textarea>
                    </div>
                    <div class="col-lg-12 text-center">
                      <button class="btn btn-primary" type="submit">Send</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Contact Section-->
    <button class="btn btn-primary" id="scrollTopBtn" type="button"><i class="fas fa-angle-up text-white"></i></button>
{% endblock %}

main_app/templates/main_page1.html
{% extends 'index.html' %}

{% block main_content %}
    <ul>
        {% for category in categories %}
            <h1>{{ category.title }}</h1> # Назва категорії
            <ul>
                {% for dish in category %} # Перебираємо всі страви які є  цій каторії (бо є метод ітер)
                    <li>
                        <div>
                          <h4>{{ dish.title }}</h4> # Додаємо назву окремої страви
                          {% if dish.is_special %} # Перевіряємо чи страва є спеціальною
                              <h3>Ця страва крута</h3> # Якщо страва спеціальна
                          {% else %}
                              <h3>А ця не дуже</h3>
                          {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>

{% endblock %}

main_app/templates/services.html
    <section id="services">
      <div class="container text-center">
        <header class="mb-5">
          <h2 class="handwriting-text">We provide the following</h2>
          <h5 class="text-uppercase text-gray-500 fw-normal">Our Specialities</h5>
        </header>
        <div class="row gy-4">
          <!-- item-->
            {% for service in services %}
                <div class="hover-icon-primary col-md-4">
                    <div class="icon mb-4 mx-auto">
                            <i class="far fa-{{ service.get_icon_display }}"></i>
                            <i class="fas fa-{{ service.get_icon_display }} "></i>
                            <i class="fas fa-{{ service.get_icon_display }} "></i>
                    </div>
                    <h5 class="text-uppercase">{{service.title}}</h5>
                    <p class="mb-0 text-muted">{{service.desc}}</p>
                </div>
            {% endfor %}
        </div>
      </div>
     </section>